import { PathWords } from 'components/admin/adminLayout/types';

export enum Page {
  HOME,
  ADMIN_LOGIN,
  ADMIN_CODE,
  ADMIN_CREATE_CODE,
  ADMIN_COLORS,
  ADMIN_CREATE_COLORS,
  ADMIN_EDIT_COLORS,
  // ADMIN_BRANDS,
  // ADMIN_CREATE_BRAND,
  // ADMIN_EDIT_BRAND,
  ADMIN_CREATE_PRODUCT,
  ADMIN_EDIT_PRODUCT,
  ADMIN_CATEGORIES,
  ADMIN_PRODUCTS,
  ADMIN_QUESTIONS,
  ADMIN_CREATE_CATEGORY,
  ADMIN_EDIT_CATEGORY,
  ADMIN_TAGS,
  ADMIN_CREATE_TAG,
  ADMIN_EDIT_TAG,
  // ADMIN_SIZES,
  // ADMIN_CREATE_SIZE,
  // ADMIN_EDIT_SIZE,
  ADMIN_REVIEWS,
  ADMIN_CHECKOUTS,
  ADMIN_CREATE_CHECKOUTS,
  ADMIN_NEWS,
  ADMIN_CREATE_NEWS,
  ADMIN_EDIT_NEWS,
  ADMIN_SETTINGS_USERS,
  ADMIN_CREATE_SETTINGS_USERS,
  ADMIN_SETTINGS_SUBSCRIBERS,
  ADMIN_BANNERS,
  ADMIN_UPDATE_BANNERS,
}

export const paths = {
  [Page.HOME]: '/',
  [Page.ADMIN_LOGIN]: '/admin/login',
  [Page.ADMIN_CODE]: '/admin/code',
  [Page.ADMIN_CREATE_CODE]: '/admin/code/create-code',
  [Page.ADMIN_CATEGORIES]: '/admin/categories',
  [Page.ADMIN_CREATE_CATEGORY]: '/admin/categories/create-category',
  [Page.ADMIN_EDIT_CATEGORY]: '/admin/categories/[id]',
  [Page.ADMIN_COLORS]: '/admin/colors',
  [Page.ADMIN_CREATE_COLORS]: '/admin/colors/create-color',
  [Page.ADMIN_EDIT_COLORS]: '/admin/colors/[id]',
  // [Page.ADMIN_BRANDS]: '/admin/brands',
  // [Page.ADMIN_CREATE_BRAND]: '/admin/brands/create-brand',
  // [Page.ADMIN_EDIT_BRAND]: '/admin/brands/[id]',
  [Page.ADMIN_PRODUCTS]: '/admin/products',
  [Page.ADMIN_QUESTIONS]: '/admin/questions',
  [Page.ADMIN_CREATE_PRODUCT]: '/admin/products/create-product',
  [Page.ADMIN_EDIT_PRODUCT]: '/admin/products/[id]',
  [Page.ADMIN_TAGS]: '/admin/tags',
  [Page.ADMIN_CREATE_TAG]: '/admin/tags/create-tag',
  [Page.ADMIN_EDIT_TAG]: '/admin/tags/[id]',
  // [Page.ADMIN_SIZES]: '/admin/sizes',
  // [Page.ADMIN_CREATE_SIZE]: '/admin/sizes/create-size',
  // [Page.ADMIN_EDIT_SIZE]: '/admin/sizes/[id]',
  [Page.ADMIN_REVIEWS]: '/admin/reviews',
  [Page.ADMIN_CHECKOUTS]: '/admin/checkouts',
  [Page.ADMIN_CREATE_CHECKOUTS]: '/admin/checkouts/create-checkout',
  [Page.ADMIN_NEWS]: '/admin/newsPosts',
  [Page.ADMIN_CREATE_NEWS]: '/admin/newsPosts/create-news',
  [Page.ADMIN_EDIT_NEWS]: '/admin/newsPosts/[id]',
  [Page.ADMIN_SETTINGS_USERS]: '/admin/settings/users',
  [Page.ADMIN_CREATE_SETTINGS_USERS]: '/admin/settings/users/create-user',
  [Page.ADMIN_SETTINGS_SUBSCRIBERS]: '/admin/settings/subscribers',
  [Page.ADMIN_BANNERS]: '/admin/banners',
  [Page.ADMIN_UPDATE_BANNERS]: '/admin/banners/update-banner',
};
